# -*- coding: utf-8 -*-
"""lora_finetuned_financial_mode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11kuh_28T9S8Z0oHz1Bj_CkbgUFeaezls

This is the notebook to finetune the QWEN 2.5 Instruct Model

Make sure to be using the A100 GPU on Google Colab
"""
"""
!pip install -q --upgrade transformers datasets peft bitsandbytes accelerate trl

!pip install -q "pyarrow==16.1.0" "datasets>=3.0.0"

!pip install -q "transformers==4.47.0" "trl==0.14.0"
"""

from datasets import load_dataset
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from trl import SFTTrainer, SFTConfig
import trl

print(f"TRL version: {trl.__version__}")

# Step 4: Load dataset
ds1 = load_dataset("bilalRahib/fiqa-personal-finance-dataset")

df = ds1["train"].map(lambda x: {
    "instruction": "Answer the following personal finance question.",
    "input": x["input"],
    "output": x["output"],
})

print(f"Total examples: {len(df)}")

# Step 5: Tokenizer

BASE_MODEL = "Qwen/Qwen2.5-7B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL, use_fast=True)

tokenizer.pad_token = tokenizer.eos_token

tokenizer.padding_side = "right"

# Step 6: Format function

def format_example(x):
    return (
        f"### Instruction:\n{x['instruction']}\n\n"

        f"### Input:\n{x['input']}\n\n"

        f"### Response:\n{x['output']}"
    )

# Step 7: Check average sequence length

lengths = [len(tokenizer(format_example(x))["input_ids"]) for x in df.select(range(500))]
avg_len = sum(lengths) // len(lengths)

max_len = max(lengths)

print(f"Sequence lengths — avg: {avg_len}, max: {max_len}")

MAX_LEN = min(max_len, 512)
print(f"Using max_length: {MAX_LEN}")

# Step 8: 4-bit quantization config
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)

# Step 9: Load model
model = AutoModelForCausalLM.from_pretrained(

    BASE_MODEL,
    quantization_config=bnb_config,

    device_map="auto",
    attn_implementation="eager",
)

#  Step 10: Prepare for k-bit training
#k-bit training for 4-bit quantinization(best for 0-shot prompting)
model = prepare_model_for_kbit_training(model)

#  Step 11: LoRA config


#configures lora with r=8 meaning axr and bxr will have a value of 8 reducing parameters trained by almost 99%
lora_config = LoraConfig(

    r=8,
    lora_alpha=16,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                    "gate_proj", "up_proj", "down_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",

)


model = get_peft_model(model, lora_config)
model.print_trainable_parameters()


trl_version = tuple(int(x) for x in trl.__version__.split(".")[:2])
max_len_kwarg = "max_length" if trl_version >= (0, 16) else "max_seq_length"

args = SFTConfig(
    output_dir="qwen2.5-7b-finance-lora",
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,
    num_train_epochs=1,
    learning_rate=2e-4,
    bf16=True,
    logging_steps=20,
    save_steps=200,
    save_total_limit=2,
    gradient_checkpointing=True,
    warmup_steps=100,
    lr_scheduler_type="cosine",
    #try lion and normal adam
    optim="paged_adamw_8bit",
    report_to="none",
    packing=True,
    **{max_len_kwarg: MAX_LEN},
)

# Step 13: Trainer
trainer_kwargs = dict(
    model=model,
    train_dataset=df,
    formatting_func=format_example,
    args=args,
)

if trl_version >= (0, 12):
    trainer_kwargs["processing_class"] = tokenizer
else:
    trainer_kwargs["tokenizer"] = tokenizer

trainer = SFTTrainer(**trainer_kwargs)

#  Step 14: Train


trainer.train()

#  Step 15: Save


trainer.save_model("qwen2.5-7b-finance-lora")
tokenizer.save_pretrained("qwen2.5-7b-finance-lora")
print("Training complete. Model saved to qwen2.5-7b-finance-lora/")

#!zip -r qwen2.5-7b-finance-lora.zip qwen2.5-7b-finance-lora/

from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer

# Load and merge
base_model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen2.5-7B-Instruct")
model = PeftModel.from_pretrained(base_model, "qwen2.5-7b-finance-lora")
merged_model = model.merge_and_unload()

# Save merged model
merged_model.save_pretrained("qwen2.5-7b-merged")

# Save tokenizer directly from the base model (not the adapter folder)
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2.5-7B-Instruct")
tokenizer.save_pretrained("qwen2.5-7b-merged")

"""Copied code from ggerganov github to convert into gguf file for inference"""

'''
!git clone https://github.com/ggerganov/llama.cpp
!pip install -q -r llama.cpp/requirements.txt

!cmake llama.cpp -B llama.cpp/build
!cmake --build llama.cpp/build --config Release -j4

!python llama.cpp/convert_hf_to_gguf.py qwen2.5-7b-merged \
    --outfile qwen2.5-7b-finance-f16.gguf \
    --outtype f16

"""quantinized to 4 bits per weight"""

!cmake llama.cpp -B llama.cpp/build
!cmake --build llama.cpp/build --config Release -j4

!./llama.cpp/build/bin/llama-quantize \
    qwen2.5-7b-finance-f16.gguf \
    qwen2.5-7b-finance-q4km.gguf \
    q4_k_m

!ls -lh qwen2.5-7b-finance-f16.gguf
!ls -lh qwen2.5-7b-finance-q4km.gguf

!ls -lh qwen2.5-7b-finance-q4km.gguf

from google.colab import files
files.download('qwen2.5-7b-finance-q4km.gguf')

!zip -r qwen2.5-7b-finance.gguf.zip qwen2.5-7b-finance.gguf
'''